apiVersion: run.ai/v2alpha1
kind: InteractivePolicy
metadata:
  name: interactive-policy1
spec:
  name:
    rules:
      required: true
  gpu:
    rules:
      required: true
      min: "0"  #
      max: "1"
    value: "0"
  requestedCpu:
    rules:
      required: true
      min: "0"  #
      max: "4"
    value: "0"
  cpuLimit:
    rules:
      required: true
      min: "0"  #
      max: "4"
    value: "0"
  migProfile:
    rules:
      required: true
      canEdit: false
  mpi:
    rules:
      canEdit: false
    value: false
  pvcs:
    rules:
      canAdd: false
  preemptible:
    rukes:
      canEdit: false
    value: false 
